"""add_export_book_table_table

Revision ID: 053b59b3a147
Revises: cd08914a0683
Create Date: 2026-06-02 21:21:56.769959

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "053b59b3a147"
down_revision: str | Sequence[str] | None = "cd08914a0683"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_books",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("export_filename", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PENDING",
                "COMPLETED",
                "FAILED",
                "REMOVED",
                name="BookActionStatusEnum",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum("HTML", "PDF", name="formattypeenum", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_books_book_id"), "export_books", ["book_id"], unique=False
    )
    op.create_index(op.f("ix_export_books_id"), "export_books", ["id"], unique=False)
    op.drop_index(op.f("ix_complete_books_book_id"), table_name="complete_books")
    op.drop_index(op.f("ix_complete_books_id"), table_name="complete_books")
    op.drop_table("complete_books")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complete_books",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("format", sa.VARCHAR(length=40), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_expired",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("complete_books_book_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("complete_books_pkey")),
    )
    op.create_index(
        op.f("ix_complete_books_id"), "complete_books", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_complete_books_book_id"), "complete_books", ["book_id"], unique=False
    )
    op.drop_index(op.f("ix_export_books_id"), table_name="export_books")
    op.drop_index(op.f("ix_export_books_book_id"), table_name="export_books")
    op.drop_table("export_books")
    # ### end Alembic commands ###
