"""add_upload_book_converters_table

Revision ID: 8ef3f651bffd
Revises: 2e006f69a525
Create Date: 2026-06-18 20:21:45.754008

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8ef3f651bffd"
down_revision: str | Sequence[str] | None = "2e006f69a525"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_book_converters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PENDING",
                "COMPLETED",
                "FAILED",
                "REMOVED",
                name="bookactionstatusenum",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_book_converters_book_id"),
        "upload_book_converters",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_upload_book_converters_id"),
        "upload_book_converters",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_upload_book_converters_id"), table_name="upload_book_converters"
    )
    op.drop_index(
        op.f("ix_upload_book_converters_book_id"), table_name="upload_book_converters"
    )
    op.drop_table("upload_book_converters")
    # ### end Alembic commands ###
