"""add_soft_delete_to_books_table

Revision ID: c6f14c0d5694
Revises: 053b59b3a147
Create Date: 2026-06-03 21:30:17.551712

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c6f14c0d5694"
down_revision: str | Sequence[str] | None = "053b59b3a147"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("books", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "export_books", "book_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "export_books", "book_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("books", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("books", "deleted_at")
    # ### end Alembic commands ###
