"""add_columns_to_export_books_table

Revision ID: cb5789296b60
Revises: c6f14c0d5694
Create Date: 2026-06-04 19:34:32.573458

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cb5789296b60"
down_revision: str | Sequence[str] | None = "c6f14c0d5694"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "export_books",
        sa.Column(
            "template",
            sa.Enum(
                "SIMPLE_TEST", name="templatetypeenum", native_enum=False, length=40
            ),
            nullable=True,
        ),
    )
    op.add_column("export_books", sa.Column("characters", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("export_books", "characters")
    op.drop_column("export_books", "template")
    # ### end Alembic commands ###
