"""Add jobs Table

Revision ID: cc2df0548c27
Revises: 9f238039f020
Create Date: 2026-05-03 13:54:08.488543

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cc2df0548c27"
down_revision: str | Sequence[str] | None = "9f238039f020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("object_table", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="jobstatusenum",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("BOOK_PARSING", name="jobtypeenum", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("count_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    op.create_index(op.f("ix_jobs_object_id"), "jobs", ["object_id"], unique=False)
    op.create_index(
        op.f("ix_jobs_object_table"), "jobs", ["object_table"], unique=False
    )
    op.create_index(
        "ix_jobs_object_table_id", "jobs", ["object_table", "object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_object_table_id", table_name="jobs")
    op.drop_index(op.f("ix_jobs_object_table"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_object_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
