"""add_is_expired_column_to_complete_books_table

Revision ID: cd08914a0683
Revises: fda2c0bf173e
Create Date: 2026-06-02 17:39:43.986600

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cd08914a0683"
down_revision: str | Sequence[str] | None = "fda2c0bf173e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complete_books",
        sa.Column(
            "is_expired", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complete_books", "is_expired")
    # ### end Alembic commands ###
