"""Add Complete Book Model

Revision ID: fda2c0bf173e
Revises: cc2df0548c27
Create Date: 2026-05-04 15:50:14.694943

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fda2c0bf173e"
down_revision: str | Sequence[str] | None = "cc2df0548c27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complete_books",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "format",
            sa.Enum("HTML", "PDF", name="formattypeenum", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complete_books_book_id"), "complete_books", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_complete_books_id"), "complete_books", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_complete_books_id"), table_name="complete_books")
    op.drop_index(op.f("ix_complete_books_book_id"), table_name="complete_books")
    op.drop_table("complete_books")
    # ### end Alembic commands ###
